// Auto-generated WASM operator bindings
// DO NOT EDIT - Generated by scripts/generate-wasm-bindings.js
// Run 'npm run wasm:generate' to regenerate this file

export type OperatorType = 'gradient' | 'moving_blob' | 'perlin_noise' | 'rainbow' | 'sparkle' | 'strobe';

// WASM module interface
interface WasmModule {
    _create_context(width: number, height: number): number;
    _destroy_context(contextPtr: number): void;
    _set_timing(contextPtr: number, timestamp: number, deltaTime: number): void;
    _set_parameters(contextPtr: number, paramsPtr: number, paramCount: number): void;
    _get_output_buffer(contextPtr: number): number;
    _get_buffer_size(contextPtr: number): number;
    _call_gradient_operator(contextPtr: number): void;
    _call_moving_blob_operator(contextPtr: number): void;
    _call_perlin_noise_operator(contextPtr: number): void;
    _call_rainbow_operator(contextPtr: number): void;
    _call_sparkle_operator(contextPtr: number): void;
    _call_strobe_operator(contextPtr: number): void;
    
    // Memory access
    HEAPU8: Uint8Array;
    HEAPU32: Uint32Array;
    HEAPF32: Float32Array;
    _malloc(size: number): number;
    _free(ptr: number): void;
}

let wasmModule: WasmModule | null = null;
let wasmLoadPromise: Promise<WasmModule> | null = null;

// Operator definitions (auto-generated from C++ source)
export const NATIVE_OPERATOR_DEFINITIONS = [
  {
    name: 'Gradient (Native)',
    type: 'native_gradient',
    params: [
      { label: 'Angle', name: 'angle', type: 'float', default: 0, min: 0, max: 360 },
      { label: 'Start Hue', name: 'start_hue', type: 'float', default: 0, min: 0, max: 255 },
      { label: 'End Hue', name: 'end_hue', type: 'float', default: 255, min: 0, max: 255 },
      { label: 'Saturation', name: 'saturation', type: 'float', default: 255, min: 0, max: 255 },
      { label: 'Value', name: 'value', type: 'float', default: 255, min: 0, max: 255 }
    ]
  },
  {
    name: 'Moving Blob (Native)',
    type: 'native_moving_blob',
    params: [
      { label: 'Speed', name: 'speed', type: 'float', default: 30, min: 0, max: 100 },
      { label: 'Blob Size', name: 'blob_size', type: 'float', default: 0.3, min: 0.1, max: 1 },
      { label: 'Hue', name: 'hue', type: 'float', default: 0, min: 0, max: 255 },
      { label: 'Saturation', name: 'saturation', type: 'float', default: 255, min: 0, max: 255 },
      { label: 'Value', name: 'value', type: 'float', default: 255, min: 0, max: 255 }
    ]
  },
  {
    name: 'Perlin Noise (Native)',
    type: 'native_perlin_noise',
    params: [
      { label: 'Scale', name: 'scale', type: 'float', default: 4, min: 1, max: 20 },
      { label: 'Speed', name: 'speed', type: 'float', default: 50, min: 0, max: 200 },
      { label: 'Base Hue', name: 'hue_base', type: 'float', default: 0, min: 0, max: 255 },
      { label: 'Hue Range', name: 'hue_range', type: 'float', default: 60, min: 0, max: 255 },
      { label: 'Saturation', name: 'saturation', type: 'float', default: 255, min: 0, max: 255 },
      { label: 'Value', name: 'value', type: 'float', default: 255, min: 0, max: 255 }
    ]
  },
  {
    name: 'Rainbow (Native)',
    type: 'native_rainbow',
    params: [
      { label: 'Speed', name: 'speed', type: 'float', default: 0.1, min: 0, max: 1 },
      { label: 'Saturation', name: 'saturation', type: 'float', default: 1, min: 0, max: 1 },
      { label: 'Value', name: 'value', type: 'float', default: 1, min: 0, max: 1 },
      { label: 'Angle', name: 'angle', type: 'float', default: 0, min: 0, max: 360 }
    ]
  },
  {
    name: 'Sparkle (Native)',
    type: 'native_sparkle',
    params: [
      { label: 'Density', name: 'density', type: 'float', default: 0.1, min: 0, max: 1 },
      { label: 'Fade Rate', name: 'fade_rate', type: 'float', default: 0.95, min: 0.5, max: 0.99 },
      { label: 'Hue', name: 'hue', type: 'float', default: 255, min: 0, max: 255 },
      { label: 'Saturation', name: 'saturation', type: 'float', default: 255, min: 0, max: 255 },
      { label: 'Value', name: 'value', type: 'float', default: 255, min: 0, max: 255 }
    ]
  },
  {
    name: 'Strobe (Native)',
    type: 'native_strobe',
    params: [
      { label: 'Rate (Hz)', name: 'rate', type: 'float', default: 2, min: 0.1, max: 20 },
      { label: 'Duty Cycle', name: 'duty_cycle', type: 'float', default: 0.1, min: 0.01, max: 0.9 },
      { label: 'Hue', name: 'hue', type: 'float', default: 0, min: 0, max: 255 },
      { label: 'Saturation', name: 'saturation', type: 'float', default: 0, min: 0, max: 255 },
      { label: 'Value', name: 'value', type: 'float', default: 255, min: 0, max: 255 }
    ]
  }
];

// Load WASM module
export async function loadWasmModule(): Promise<WasmModule> {
    if (wasmModule) {
        return wasmModule;
    }
    
    if (wasmLoadPromise) {
        return wasmLoadPromise;
    }
    
    wasmLoadPromise = new Promise<WasmModule>(async (resolve, reject) => {
        try {
            // Check if FastLEDPatterns is already available (script already loaded)
            const existingFactory = (window as any).FastLEDPatterns;
            if (existingFactory) {
                try {
                    const module = await existingFactory();
                    wasmModule = module as WasmModule;
                    resolve(wasmModule);
                    return;
                } catch (error) {
                    console.error('Failed to initialize existing WASM module:', error);
                    reject(error);
                    return;
                }
            }
            
            // Use dynamic script loading instead of import() to avoid Vite restrictions
            const script = document.createElement('script');
            script.src = '/wasm/fastled_patterns.js';
            script.type = 'text/javascript';
            
            script.onload = async () => {
                try {
                    const wasmFactory = (window as any).FastLEDPatterns;
                    if (!wasmFactory) {
                        throw new Error('FastLEDPatterns factory not found on window');
                    }
                    
                    const module = await wasmFactory();
                    wasmModule = module as WasmModule;
                    resolve(wasmModule);
                } catch (error) {
                    console.error('Failed to initialize WASM module:', error);
                    reject(error);
                }
            };
            
            script.onerror = () => {
                reject(new Error('Failed to load WASM script'));
            };
            
            document.head.appendChild(script);
        } catch (error) {
            console.error('Failed to load WASM module:', error);
            reject(error);
        }
    });
    
    return wasmLoadPromise;
}

// Operator runner that manages WASM calls
export class FastLEDWasmOperatorRunner {
    private module: WasmModule;
    private contextPtr: number = 0;
    private paramsPtr: number = 0;
    private width: number;
    private height: number;

    constructor(module: WasmModule, width: number, height: number) {
        this.module = module;
        this.width = width;
        this.height = height;
        this.contextPtr = this.module._create_context(width, height);
        if (!this.contextPtr) {
            throw new Error('Failed to create WASM operator context');
        }
    }

    destroy() {
        if (this.contextPtr) {
            this.module._destroy_context(this.contextPtr);
            this.contextPtr = 0;
        }
        if (this.paramsPtr) {
            this.module._free(this.paramsPtr);
            this.paramsPtr = 0;
        }
    }

    setTiming(timestamp: number, deltaTime: number) {
        if (!this.contextPtr) return;
        this.module._set_timing(this.contextPtr, timestamp, deltaTime);
    }

    setParameters(params: number[]) {
        if (!this.contextPtr) return;
        
        // Free existing parameter buffer
        if (this.paramsPtr) {
            this.module._free(this.paramsPtr);
        }
        
        // Allocate new parameter buffer
        const paramSize = params.length * 4; // 4 bytes per float
        this.paramsPtr = this.module._malloc(paramSize);
        
        // Copy parameters to WASM memory
        const paramView = new Float32Array(this.module.HEAPU8.buffer, this.paramsPtr, params.length);
        for (let i = 0; i < params.length; i++) {
            paramView[i] = params[i];
        }
        
        // Set parameters in context
        this.module._set_parameters(this.contextPtr, this.paramsPtr, params.length);
    }

    async runGradient(): Promise<ImageData | null> {
        if (!this.contextPtr) return null;
        this.module._call_gradient_operator(this.contextPtr);
        return this.getImageData();
    }

    async runMovingBlob(): Promise<ImageData | null> {
        if (!this.contextPtr) return null;
        this.module._call_moving_blob_operator(this.contextPtr);
        return this.getImageData();
    }

    async runPerlinNoise(): Promise<ImageData | null> {
        if (!this.contextPtr) return null;
        this.module._call_perlin_noise_operator(this.contextPtr);
        return this.getImageData();
    }

    async runRainbow(): Promise<ImageData | null> {
        if (!this.contextPtr) return null;
        this.module._call_rainbow_operator(this.contextPtr);
        return this.getImageData();
    }

    async runSparkle(): Promise<ImageData | null> {
        if (!this.contextPtr) return null;
        this.module._call_sparkle_operator(this.contextPtr);
        return this.getImageData();
    }

    async runStrobe(): Promise<ImageData | null> {
        if (!this.contextPtr) return null;
        this.module._call_strobe_operator(this.contextPtr);
        return this.getImageData();
    }

    private getImageData(): ImageData | null {
        if (!this.contextPtr) return null;
        
        try {
            const bufferPtr = this.module._get_output_buffer(this.contextPtr);
            const bufferSize = this.module._get_buffer_size(this.contextPtr);
            
            if (!bufferPtr || bufferSize !== this.width * this.height * 3) {
                console.error('Invalid WASM buffer');
                return null;
            }
            
            // Create ImageData from WASM buffer
            const imageData = new ImageData(this.width, this.height);
            const rgbBuffer = new Uint8Array(this.module.HEAPU8.buffer, bufferPtr, bufferSize);
            
            // Convert RGB to RGBA
            for (let i = 0; i < this.width * this.height; i++) {
                const rgbIndex = i * 3;
                const rgbaIndex = i * 4;
                imageData.data[rgbaIndex] = rgbBuffer[rgbIndex];     // R
                imageData.data[rgbaIndex + 1] = rgbBuffer[rgbIndex + 1]; // G
                imageData.data[rgbaIndex + 2] = rgbBuffer[rgbIndex + 2]; // B
                imageData.data[rgbaIndex + 3] = 255; // A
            }
            
            return imageData;
        } catch (error) {
            console.error('Failed to get image data from WASM:', error);
            return null;
        }
    }
}

export interface NativeOperatorParams {
    angle?: number;
    start_hue?: number;
    end_hue?: number;
    saturation?: number;
    value?: number;
    speed?: number;
    blob_size?: number;
    hue?: number;
    scale?: number;
    hue_base?: number;
    hue_range?: number;
    density?: number;
    fade_rate?: number;
    rate?: number;
    duty_cycle?: number;
}

// Main render function - generalized for all operators
export async function renderNativeOperator(
    operatorName: OperatorType,
    width: number,
    height: number,
    timestamp: number,
    params: NativeOperatorParams = {}
): Promise<ImageData | null> {
    try {
        const module = await loadWasmModule();
        const runner = new FastLEDWasmOperatorRunner(module, width, height);
        
        // Set timing
        runner.setTiming(timestamp, 16.67); // Assume ~60fps
        
        // Find operator definition
        const operatorDef = NATIVE_OPERATOR_DEFINITIONS.find(def => 
            def.type === `native_${operatorName}`
        );
        
        if (!operatorDef) {
            throw new Error(`Unknown operator: ${operatorName}`);
        }
        
        // Extract parameter values in order
        const paramValues = operatorDef.params.map(param => 
            params[param.name as keyof NativeOperatorParams] ?? param.default
        );
        
        // Set parameters
        runner.setParameters(paramValues);
        
        // Run the appropriate operator
        let result: ImageData | null = null;
        switch (operatorName) {
        case 'gradient':
            return await runner.runGradient();
        case 'moving_blob':
            return await runner.runMovingBlob();
        case 'perlin_noise':
            return await runner.runPerlinNoise();
        case 'rainbow':
            return await runner.runRainbow();
        case 'sparkle':
            return await runner.runSparkle();
        case 'strobe':
            return await runner.runStrobe();
            default:
                throw new Error(`Unhandled operator: ${operatorName}`);
        }
        
        runner.destroy();
        return result;
        
    } catch (error) {
        console.error('Failed to render native operator:', error);
        return null;
    }
}
