#pragma once

// Firmware Version - This will be updated by the release script
// Format: fwvX.Y.Z
#define FIRMWARE_VERSION "fwv0.0.5"

// Hardware Version - Manually update this if hardware changes
// Format: hwvX.Y.Z
#define HARDWARE_VERSION "hwv0.0.1"

// --- Firmware Signature Verification ---
// ECDSA P-256 Public Key (Raw 64-byte format: 32-byte X + 32-byte Y coordinates)
// This will be populated when keys are generated
#define FIRMWARE_SIGNATURE_PUBLIC_KEY_HEX "PLACEHOLDER_WILL_BE_REPLACED_WITH_ACTUAL_PUBLIC_KEY_HEX"

// ECDSA P-256 Public Key (64 bytes: 32-byte X + 32-byte Y coordinates)
// Generated by scripts/generate-signing-keys.sh
static const uint8_t FIRMWARE_PUBLIC_KEY[64] = {
    0x81, 0x9d, 0x21, 0x53, 0x2d, 0x00, 0x6b, 0x37, 0x00, 0xce, 0x71, 0xb9, 0x3b, 0x8a, 0xf3, 0xc6,
    0x1c, 0xd4, 0x3e, 0x73, 0x2d, 0x2b, 0xf5, 0xb6, 0x52, 0x71, 0xb9, 0x12, 0xfa, 0xd1, 0xb9, 0xd1,
    0x03, 0x7a, 0x2c, 0xf1, 0x5c, 0xf9, 0x1b, 0x49, 0x5d, 0xf8, 0xe6, 0x9a, 0x6f, 0x96, 0x62, 0xd4,
    0x86, 0x6b, 0xdf, 0x4d, 0x83, 0xfd, 0xfc, 0x74, 0x65, 0xd4, 0x9f, 0x98, 0xec, 0x34, 0x5a, 0xc1
};

// ECDSA P-256 signature is 64 bytes (32-byte r + 32-byte s)
#define FIRMWARE_SIGNATURE_LENGTH 64


// You can add other build-time constants here if needed,
// for example, a build timestamp or specific capabilities.
