#pragma once

// Firmware Version - This will be updated by the release script
// Format: fwvX.Y.Z
#define FIRMWARE_VERSION "fwv0.0.17"

// Hardware Version - Manually update this if hardware changes
// Format: hwvX.Y.Z
#define HARDWARE_VERSION "hwv0.0.1"

// --- Firmware Signature Verification ---
// ECDSA P-256 Public Key (Raw 64-byte format: 32-byte X + 32-byte Y coordinates)
// This will be populated when keys are generated
#define FIRMWARE_SIGNATURE_PUBLIC_KEY_HEX "PLACEHOLDER_WILL_BE_REPLACED_WITH_ACTUAL_PUBLIC_KEY_HEX"

// ECDSA P-256 Public Key (64 bytes: 32-byte X + 32-byte Y coordinates)
// Generated by scripts/generate-signing-keys.sh - UPDATED to match current keys
static const uint8_t FIRMWARE_PUBLIC_KEY[64] = {
    0x50, 0x6e, 0x3d, 0x2c, 0xe4, 0xe9, 0xf6, 0xe7, 0xf7, 0x7b, 0xe2, 0x6e, 0x16, 0x3c, 0xb8, 0xb3,
    0x49, 0xaa, 0x6d, 0x69, 0x69, 0xdd, 0xa3, 0x54, 0x0f, 0x62, 0x67, 0x15, 0x9e, 0xdf, 0x73, 0x7f,
    0x88, 0x4b, 0xb1, 0x3e, 0x11, 0xaf, 0x49, 0xaf, 0x9d, 0x24, 0x5d, 0xe4, 0x4b, 0x26, 0x12, 0xc2,
    0x76, 0x59, 0xc4, 0xf2, 0xaa, 0xe2, 0xb0, 0xb8, 0x13, 0x4b, 0x7d, 0x82, 0x81, 0x7f, 0x15, 0x4d
};

// ECDSA P-256 signature is 64 bytes (32-byte r + 32-byte s)
#define FIRMWARE_SIGNATURE_LENGTH 64


// You can add other build-time constants here if needed,
// for example, a build timestamp or specific capabilities.
