// Auto-generated operator header file
// DO NOT EDIT - Generated by scripts/generate-native-code.js
// Run 'npm run wasm:generate' to regenerate this file
//
// This file provides the main header for FastLED operators with 2D buffer support.
// Operator function declarations and parameter arrays are auto-generated from 
// the individual operator source files.

#ifndef FASTLED_OPERATORS_H
#define FASTLED_OPERATORS_H

#include <stdint.h>
#include <stdbool.h>
#include <cmath>

#if defined(__EMSCRIPTEN__) || defined(NATIVE_BUILD)
// WASM or native test build - provide essential FastLED-compatible types and functions
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

// CRGB color type (compatible with FastLED)
struct CRGB {
    uint8_t r, g, b;
    
    CRGB() : r(0), g(0), b(0) {}
    CRGB(uint8_t red, uint8_t green, uint8_t blue) : r(red), g(green), b(blue) {}
    
    // Assignment from CHSV
    CRGB& operator=(const struct CHSV& hsv);
};

// CHSV color type (compatible with FastLED)
struct CHSV {
    uint8_t h, s, v;
    
    CHSV() : h(0), s(0), v(0) {}
    CHSV(uint8_t hue, uint8_t sat, uint8_t val) : h(hue), s(sat), v(val) {}
    
    // Conversion to CRGB
    operator CRGB() const;
};

// FastLED-compatible timing functions
uint8_t beat8(uint16_t beats_per_minute, uint32_t timebase = 0);
uint16_t beat16(uint16_t beats_per_minute, uint32_t timebase = 0);

// FastLED-compatible noise functions
uint8_t inoise8(uint16_t x, uint16_t y = 0, uint16_t z = 0);
uint16_t inoise16(uint16_t x, uint16_t y = 0, uint16_t z = 0);

// FastLED-compatible math functions
uint8_t scale8(uint8_t i, uint8_t scale);
uint16_t scale16(uint16_t i, uint16_t scale);
uint8_t sin8(uint8_t theta);
uint8_t cos8(uint8_t theta);
uint8_t random8();
uint8_t random8(uint8_t max);
uint16_t random16();
uint16_t random16(uint16_t max);
uint8_t qadd8(uint8_t a, uint8_t b);
uint8_t qsub8(uint8_t a, uint8_t b);
uint8_t dim8_raw(uint8_t x);
uint8_t brighten8_raw(uint8_t x);

// FastLED-compatible blend functions
CRGB blend(const CRGB& a, const CRGB& b, uint8_t amount);

#else
// ESP32 build - use standard FastLED
#include <FastLED.h>
#endif

// Operator context structure with 2D buffer
typedef struct {
    CRGB* color_buffer;       // 2D color buffer (width * height)
    CRGB* input_buffer1;      // First input buffer (for blend operations)
    CRGB* input_buffer2;      // Second input buffer (for blend operations)
    uint32_t width;           // Buffer width in pixels
    uint32_t height;          // Buffer height in pixels
    uint32_t timestamp_ms;    // Current timestamp in milliseconds
    uint32_t delta_time_ms;   // Time since last call in milliseconds
    bool is_starting;         // True if operator is being initialized
    bool is_ending;           // True if operator is being cleaned up
    float* parameters;        // Array of parameter values
    uint32_t param_count;     // Number of parameters
} OperatorContext;

// Parameter definition structure
typedef struct {
    const char* name;
    const char* label;
    const char* type;         // "float", "int", "color", "select"
    float default_value;
    float min_value;
    float max_value;
    const char** options;     // For select type parameters
    uint32_t option_count;
} OperatorParameter;

// Operator definition structure
typedef struct {
    const char* name;
    const char* type;
    const OperatorParameter* parameters;
    uint32_t param_count;
    void (*operator_func)(OperatorContext* ctx);
} OperatorDefinition;

// Auto-generated operator function declarations
extern "C" {
    void gradient_operator(OperatorContext* ctx);
    void moving_blob_operator(OperatorContext* ctx);
    void perlin_noise_operator(OperatorContext* ctx);
    void rainbow_operator(OperatorContext* ctx);
    void sparkle_operator(OperatorContext* ctx);
    void strobe_operator(OperatorContext* ctx);
}

// Auto-generated operator parameter array declarations
extern const OperatorParameter gradient_params[];
extern const OperatorParameter moving_blob_params[];
extern const OperatorParameter perlin_noise_params[];
extern const OperatorParameter rainbow_params[];
extern const OperatorParameter sparkle_params[];
extern const OperatorParameter strobe_params[];

// Operator registry (defined in operator_registry.cpp)
extern const OperatorDefinition OPERATOR_DEFINITIONS[];
extern const uint32_t OPERATOR_COUNT;

// Utility functions for 2D buffer access
inline void set_pixel(OperatorContext* ctx, uint32_t x, uint32_t y, CRGB color) {
    if (x < ctx->width && y < ctx->height) {
        ctx->color_buffer[y * ctx->width + x] = color;
    }
}

inline CRGB get_pixel(OperatorContext* ctx, uint32_t x, uint32_t y) {
    if (x < ctx->width && y < ctx->height) {
        return ctx->color_buffer[y * ctx->width + x];
    }
    return CRGB(0, 0, 0);
}

inline CRGB get_input1_pixel(OperatorContext* ctx, uint32_t x, uint32_t y) {
    if (ctx->input_buffer1 && x < ctx->width && y < ctx->height) {
        return ctx->input_buffer1[y * ctx->width + x];
    }
    return CRGB(0, 0, 0);
}

inline CRGB get_input2_pixel(OperatorContext* ctx, uint32_t x, uint32_t y) {
    if (ctx->input_buffer2 && x < ctx->width && y < ctx->height) {
        return ctx->input_buffer2[y * ctx->width + x];
    }
    return CRGB(0, 0, 0);
}

// Utility function to get normalized coordinates (0.0 to 1.0)
inline float get_normalized_x(OperatorContext* ctx, uint32_t x) {
    return (float)x / (float)(ctx->width - 1);
}

inline float get_normalized_y(OperatorContext* ctx, uint32_t y) {
    return (float)y / (float)(ctx->height - 1);
}

// Clear the entire buffer
inline void clear_buffer(OperatorContext* ctx, CRGB color = CRGB(0, 0, 0)) {
    uint32_t total_pixels = ctx->width * ctx->height;
    for (uint32_t i = 0; i < total_pixels; i++) {
        ctx->color_buffer[i] = color;
    }
}

#endif // FASTLED_OPERATORS_H
