// Auto-generated operator registry
// DO NOT EDIT - Generated by scripts/generate-native-code.js
// Run 'npm run wasm:generate' to regenerate this file
//
// This file contains the registry of all available FastLED operators.
// The registry is automatically built from the individual operator source files.

#include "fastled_patterns.h"

// Auto-generated operator registry - parameters are defined alongside their functions
const PatternDefinition PATTERN_DEFINITIONS[] = {
    {"Gradient", "gradient", gradient_params, 5, gradient_pattern},
    {"Moving Blob", "moving_blob", moving_blob_params, 5, moving_blob_pattern},
    {"Perlin Noise", "perlin_noise", perlin_noise_params, 6, perlin_noise_pattern},
    {"Rainbow", "rainbow", rainbow_params, 4, rainbow_pattern},
    {"Sparkle", "sparkle", sparkle_params, 5, sparkle_pattern},
    {"Strobe", "strobe", strobe_params, 5, strobe_pattern}
};

const uint32_t PATTERN_COUNT = sizeof(PATTERN_DEFINITIONS) / sizeof(PatternDefinition);
