// Auto-generated operator test suite
// DO NOT EDIT - Generated by scripts/generate-native-code.js
// Run 'npm run wasm:generate' to regenerate this file
//
// This file provides comprehensive testing for FastLED operators.
// It tests each operator with various parameter combinations to catch:
// - Crashes (segfaults, divide by zero)
// - Infinite loops 
// - Parameter type/range issues
// - Memory leaks

#include "fastled_operators.h"
#include <iostream>
#include <vector>
#include <chrono>
#include <cmath>
#include <signal.h>
#include <setjmp.h>

// Test configuration
const uint32_t TEST_WIDTH = 16;
const uint32_t TEST_HEIGHT = 16;
const uint32_t MAX_EXECUTION_TIME_MS = 1000; // 1 second max per test
const uint32_t TEST_ITERATIONS = 10;

// Global test state
static jmp_buf crash_recovery;
static bool test_crashed = false;

// Signal handler for crashes
void crash_handler(int signal) {
    test_crashed = true;
    longjmp(crash_recovery, signal);
}

// Test result structure
struct TestResult {
    std::string operator_name;
    std::string test_case;
    bool passed;
    std::string error_message;
    uint32_t execution_time_ms;
};

// Operator context wrapper for testing
class TestOperatorContext {
private:
    OperatorContext* ctx;
    
public:
    TestOperatorContext(uint32_t width, uint32_t height) {
        ctx = (OperatorContext*)malloc(sizeof(OperatorContext));
        if (!ctx) {
            throw std::runtime_error("Failed to allocate operator context");
        }
        
        // Allocate 2D color buffer
        uint32_t total_pixels = width * height;
        ctx->color_buffer = (CRGB*)malloc(total_pixels * sizeof(CRGB));
        if (!ctx->color_buffer) {
            free(ctx);
            throw std::runtime_error("Failed to allocate color buffer");
        }
        
        // Initialize context
        ctx->input_buffer1 = nullptr;
        ctx->input_buffer2 = nullptr;
        ctx->width = width;
        ctx->height = height;
        ctx->timestamp_ms = 0;
        ctx->delta_time_ms = 16; // ~60 FPS
        ctx->is_starting = true;
        ctx->is_ending = false;
        ctx->parameters = nullptr;
        ctx->param_count = 0;
        
        // Clear buffer
        clear_buffer(ctx, CRGB(0, 0, 0));
    }
    
    ~TestOperatorContext() {
        if (ctx) {
            if (ctx->color_buffer) free(ctx->color_buffer);
            if (ctx->input_buffer1) free(ctx->input_buffer1);
            if (ctx->input_buffer2) free(ctx->input_buffer2);
            if (ctx->parameters) free(ctx->parameters);
            free(ctx);
        }
    }
    
    void setParameters(const std::vector<float>& params) {
        if (ctx->parameters) {
            free(ctx->parameters);
            ctx->parameters = nullptr;
            ctx->param_count = 0;
        }
        
        if (!params.empty()) {
            ctx->parameters = (float*)malloc(params.size() * sizeof(float));
            if (ctx->parameters) {
                for (size_t i = 0; i < params.size(); i++) {
                    ctx->parameters[i] = params[i];
                }
                ctx->param_count = params.size();
            }
        }
    }
    
    void setTiming(uint32_t timestamp_ms) {
        ctx->timestamp_ms = timestamp_ms;
        ctx->is_starting = false;
    }
    
    OperatorContext* get() { return ctx; }
    
    // Check for obvious issues in output
    bool validateOutput() {
        if (!ctx || !ctx->color_buffer) return false;
        
        uint32_t total_pixels = ctx->width * ctx->height;
        // bool has_any_color = false; // Could be used for validation
        bool has_invalid_values = false;
        
        for (uint32_t i = 0; i < total_pixels; i++) {
            CRGB& pixel = ctx->color_buffer[i];
            
            // Check for any non-zero color (unused for now)
            // if (pixel.r > 0 || pixel.g > 0 || pixel.b > 0) {
            //     has_any_color = true;
            // }
            
            // Check for invalid values (shouldn't happen with CRGB but worth checking)
            if (pixel.r > 255 || pixel.g > 255 || pixel.b > 255) {
                has_invalid_values = true;
            }
        }
        
        // Most operators should produce some color output
        // (Strobe might not depending on timing, so we'll be lenient)
        return !has_invalid_values;
    }
};

// Test parameter generation
std::vector<std::vector<float>> generateTestParameters(const OperatorParameter* params, uint32_t param_count) {
    std::vector<std::vector<float>> test_cases;
    
    if (param_count == 0) {
        test_cases.push_back(std::vector<float>());
        return test_cases;
    }
    
    // Test case 1: Default values
    std::vector<float> defaults;
    for (uint32_t i = 0; i < param_count; i++) {
        defaults.push_back(params[i].default_value);
    }
    test_cases.push_back(defaults);
    
    // Test case 2: Minimum values
    std::vector<float> mins;
    for (uint32_t i = 0; i < param_count; i++) {
        mins.push_back(params[i].min_value);
    }
    test_cases.push_back(mins);
    
    // Test case 3: Maximum values
    std::vector<float> maxs;
    for (uint32_t i = 0; i < param_count; i++) {
        maxs.push_back(params[i].max_value);
    }
    test_cases.push_back(maxs);
    
    // Test case 4: Mid-range values
    std::vector<float> mids;
    for (uint32_t i = 0; i < param_count; i++) {
        float mid = (params[i].min_value + params[i].max_value) / 2.0f;
        mids.push_back(mid);
    }
    test_cases.push_back(mids);
    
    // Test case 5: Edge case - values just outside bounds (should be clamped)
    std::vector<float> out_of_bounds;
    for (uint32_t i = 0; i < param_count; i++) {
        float range = params[i].max_value - params[i].min_value;
        float out_of_bound = params[i].max_value + range * 0.1f; // 10% beyond max
        out_of_bounds.push_back(out_of_bound);
    }
    test_cases.push_back(out_of_bounds);
    
    // Test case 6: Zero values (potential divide-by-zero test)
    std::vector<float> zeros(param_count, 0.0f);
    test_cases.push_back(zeros);
    
    // Test case 7: Negative values (should be handled gracefully)
    std::vector<float> negatives;
    for (uint32_t i = 0; i < param_count; i++) {
        negatives.push_back(-std::abs(params[i].default_value));
    }
    test_cases.push_back(negatives);
    
    return test_cases;
}

// Execute a single test with timeout protection
TestResult runSingleTest(const std::string& operator_name, 
                        void (*operator_func)(OperatorContext*),
                        const OperatorParameter* /* params */,
                        uint32_t /* param_count */,
                        const std::vector<float>& test_params,
                        const std::string& test_case_name) {
    
    TestResult result;
    result.operator_name = operator_name;
    result.test_case = test_case_name;
    result.passed = false;
    result.execution_time_ms = 0;
    
    // Set up crash recovery
    test_crashed = false;
    signal(SIGSEGV, crash_handler);
    signal(SIGFPE, crash_handler);
    signal(SIGABRT, crash_handler);
    
    if (setjmp(crash_recovery) != 0) {
        result.error_message = "Operator crashed with signal " + std::to_string(test_crashed);
        return result;
    }
    
    try {
        TestOperatorContext test_ctx(TEST_WIDTH, TEST_HEIGHT);
        test_ctx.setParameters(test_params);
        
        auto start_time = std::chrono::high_resolution_clock::now();
        
        // Run operator multiple times to catch timing-dependent issues
        for (uint32_t iteration = 0; iteration < TEST_ITERATIONS; iteration++) {
            test_ctx.setTiming(iteration * 16); // Simulate 60 FPS timing
            
            // Check for timeout
            auto current_time = std::chrono::high_resolution_clock::now();
            auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(current_time - start_time);
            if (elapsed.count() > MAX_EXECUTION_TIME_MS) {
                result.error_message = "Operator timed out (possible infinite loop)";
                return result;
            }
            
            // Execute operator
            operator_func(test_ctx.get());
            
            // For debugging timeout issues
            if (elapsed.count() > MAX_EXECUTION_TIME_MS / 2) {
                result.error_message = "Operator running slowly (iteration " + std::to_string(iteration) + ")";
                return result;
            }
            
            // Validate output
            if (!test_ctx.validateOutput()) {
                result.error_message = "Invalid output detected";
                return result;
            }
        }
        
        auto end_time = std::chrono::high_resolution_clock::now();
        result.execution_time_ms = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time).count();
        result.passed = true;
        
    } catch (const std::exception& e) {
        result.error_message = std::string("Exception: ") + e.what();
    } catch (...) {
        result.error_message = "Unknown exception";
    }
    
    // Reset signal handlers
    signal(SIGSEGV, SIG_DFL);
    signal(SIGFPE, SIG_DFL);
    signal(SIGABRT, SIG_DFL);
    
    return result;
}

// Test all operators
std::vector<TestResult> runAllTests() {
    std::vector<TestResult> results;
    
    // Test each operator with various parameter combinations
    for (uint32_t i = 0; i < OPERATOR_COUNT; i++) {
        const OperatorDefinition& op_def = OPERATOR_DEFINITIONS[i];
        
        std::cout << "Testing operator: " << op_def.name << std::endl;
        
        // Generate test parameter sets
        auto test_param_sets = generateTestParameters(op_def.parameters, op_def.param_count);
        
        for (size_t j = 0; j < test_param_sets.size(); j++) {
            std::string test_case_name = "case_" + std::to_string(j);
            
            TestResult result = runSingleTest(
                op_def.name,
                op_def.operator_func,
                op_def.parameters,
                op_def.param_count,
                test_param_sets[j],
                test_case_name
            );
            
            results.push_back(result);
            
            if (result.passed) {
                std::cout << "  ✓ " << test_case_name << " (" << result.execution_time_ms << "ms)" << std::endl;
            } else {
                std::cout << "  ✗ " << test_case_name << " - " << result.error_message << std::endl;
            }
        }
    }
    
    return results;
}

// Print test summary
void printTestSummary(const std::vector<TestResult>& results) {
    uint32_t total_tests = results.size();
    uint32_t passed_tests = 0;
    
    std::cout << "\n=== TEST SUMMARY ===" << std::endl;
    
    for (const auto& result : results) {
        if (result.passed) {
            passed_tests++;
        }
    }
    
    std::cout << "Total tests: " << total_tests << std::endl;
    std::cout << "Passed: " << passed_tests << std::endl;
    std::cout << "Failed: " << (total_tests - passed_tests) << std::endl;
    std::cout << "Success rate: " << (100.0f * passed_tests / total_tests) << "%" << std::endl;
    
    if (passed_tests < total_tests) {
        std::cout << "\nFAILED TESTS:" << std::endl;
        for (const auto& result : results) {
            if (!result.passed) {
                std::cout << "  " << result.operator_name << " [" << result.test_case << "]: " 
                         << result.error_message << std::endl;
            }
        }
    }
}

int main() {
    std::cout << "FastLED Operator Test Suite" << std::endl;
    std::cout << "Testing " << OPERATOR_COUNT << " operators with " << TEST_ITERATIONS 
              << " iterations each" << std::endl;
    std::cout << "Buffer size: " << TEST_WIDTH << "x" << TEST_HEIGHT << std::endl;
    std::cout << "Max execution time per test: " << MAX_EXECUTION_TIME_MS << "ms" << std::endl;
    std::cout << std::endl;
    
    auto results = runAllTests();
    printTestSummary(results);
    
    // Return non-zero if any tests failed
    for (const auto& result : results) {
        if (!result.passed) {
            return 1;
        }
    }
    
    return 0;
} 