// Auto-generated WASM interface
// DO NOT EDIT - Generated by scripts/generate-native-code.js
// Run 'npm run wasm:generate' to regenerate this file
//
// This file provides the WASM interface for FastLED operators.
// Each operator gets a corresponding call_X_operator function that can be invoked from JavaScript.

#include "fastled_operators.h"
#include <emscripten.h>
#include <cstring>
#include <cstdlib>

static OperatorContext* g_context = nullptr;

extern "C" {

EMSCRIPTEN_KEEPALIVE
OperatorContext* create_context(uint32_t width, uint32_t height) {
    OperatorContext* ctx = (OperatorContext*)malloc(sizeof(OperatorContext));
    if (!ctx) return nullptr;
    
    // Allocate 2D color buffer
    uint32_t total_pixels = width * height;
    ctx->color_buffer = (CRGB*)malloc(total_pixels * sizeof(CRGB));
    if (!ctx->color_buffer) {
        free(ctx);
        return nullptr;
    }
    
    // Initialize context
    ctx->input_buffer1 = nullptr;
    ctx->input_buffer2 = nullptr;
    ctx->width = width;
    ctx->height = height;
    ctx->timestamp_ms = 0;
    ctx->delta_time_ms = 0;
    ctx->is_starting = true;
    ctx->is_ending = false;
    ctx->parameters = nullptr;
    ctx->param_count = 0;
    
    // Clear the buffer to black
    clear_buffer(ctx, CRGB(0, 0, 0));
    
    g_context = ctx;
    return ctx;
}

EMSCRIPTEN_KEEPALIVE
void destroy_context(OperatorContext* ctx) {
    if (!ctx) return;
    
    if (ctx->color_buffer) {
        free(ctx->color_buffer);
    }
    if (ctx->input_buffer1) {
        free(ctx->input_buffer1);
    }
    if (ctx->input_buffer2) {
        free(ctx->input_buffer2);
    }
    if (ctx->parameters) {
        free(ctx->parameters);
    }
    
    free(ctx);
    
    if (g_context == ctx) {
        g_context = nullptr;
    }
}

EMSCRIPTEN_KEEPALIVE
void set_timing(OperatorContext* ctx, uint32_t timestamp_ms, uint32_t delta_time_ms) {
    if (!ctx) return;
    ctx->timestamp_ms = timestamp_ms;
    ctx->delta_time_ms = delta_time_ms;
    ctx->is_starting = false; // Clear starting flag after first timing update
}

EMSCRIPTEN_KEEPALIVE
void set_parameters(OperatorContext* ctx, float* params, uint32_t param_count) {
    if (!ctx) return;
    
    // Free existing parameters
    if (ctx->parameters) {
        free(ctx->parameters);
        ctx->parameters = nullptr;
        ctx->param_count = 0;
    }
    
    if (params && param_count > 0) {
        // Allocate new parameter array
        ctx->parameters = (float*)malloc(param_count * sizeof(float));
        if (ctx->parameters) {
            memcpy(ctx->parameters, params, param_count * sizeof(float));
            ctx->param_count = param_count;
        }
    }
}

EMSCRIPTEN_KEEPALIVE
uint8_t* get_output_buffer(OperatorContext* ctx) {
    if (!ctx || !ctx->color_buffer) return nullptr;
    
    // Return pointer to the raw RGB data
    return (uint8_t*)ctx->color_buffer;
}

EMSCRIPTEN_KEEPALIVE
uint32_t get_buffer_size(OperatorContext* ctx) {
    if (!ctx) return 0;
    return ctx->width * ctx->height * 3; // 3 bytes per pixel (RGB)
}

// Auto-generated operator call functions

EMSCRIPTEN_KEEPALIVE
void call_gradient_operator(OperatorContext* ctx) {
    if (!ctx) return;
    gradient_operator(ctx);
}

EMSCRIPTEN_KEEPALIVE
void call_moving_blob_operator(OperatorContext* ctx) {
    if (!ctx) return;
    moving_blob_operator(ctx);
}

EMSCRIPTEN_KEEPALIVE
void call_perlin_noise_operator(OperatorContext* ctx) {
    if (!ctx) return;
    perlin_noise_operator(ctx);
}

EMSCRIPTEN_KEEPALIVE
void call_rainbow_operator(OperatorContext* ctx) {
    if (!ctx) return;
    rainbow_operator(ctx);
}

EMSCRIPTEN_KEEPALIVE
void call_sparkle_operator(OperatorContext* ctx) {
    if (!ctx) return;
    sparkle_operator(ctx);
}

EMSCRIPTEN_KEEPALIVE
void call_strobe_operator(OperatorContext* ctx) {
    if (!ctx) return;
    strobe_operator(ctx);
}

} // extern "C"

// Note: Exported functions for Emscripten build:
// ["_call_gradient_operator", "_call_moving_blob_operator", "_call_perlin_noise_operator", "_call_rainbow_operator", "_call_sparkle_operator", "_call_strobe_operator", "_create_context", "_destroy_context", "_set_timing", "_set_parameters", "_get_output_buffer", "_get_buffer_size", "_malloc", "_free"]
