// Generate native/text_fonts.h.
//   - FONT_5x8 / FONT_8x16: Spleen BDF (BSD-2-Clause, Frédéric Cambus) — crisp pixel fonts,
//     ideal at tiny sizes where anti-aliasing would just muddy things.
//   - FONT_16x32: rasterized from a real curved sans-serif (Helvetica/Arial) via headless
//     Chrome, thresholded to 1-bit. Spleen's 16x32 was boxy/hard to read at size; a true
//     typeface with curves reads far better on a 40px-tall display.
// Run:  node scripts/gen-fonts.mjs   (auto-downloads the Spleen BDFs to /tmp if missing)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { chromium } from 'playwright';

const FIRST = 32, LAST = 126, N = LAST - FIRST + 1;

async function ensureBdf(size) {
  const path = `/tmp/spleen-${size}.bdf`;
  if (existsSync(path)) return path;
  const url = `https://raw.githubusercontent.com/fcambus/spleen/master/spleen-${size}.bdf`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${url}: ${res.status}`);
  writeFileSync(path, Buffer.from(await res.arrayBuffer()));
  return path;
}

// --- Spleen BDF → flat row-major MSB-first bitmap (unchanged from the original) ---
function parseBdf(path, name) {
  const lines = readFileSync(path, 'utf8').split('\n');
  let W = 0, H = 0;
  for (const l of lines) if (l.startsWith('FONTBOUNDINGBOX')) { const p = l.split(/\s+/); W = +p[1]; H = +p[2]; break; }
  const bpr = Math.ceil(W / 8);
  const glyphs = new Map();
  let enc = -1, inBitmap = false, rows = [];
  for (const l of lines) {
    if (l.startsWith('ENCODING')) { enc = +l.split(/\s+/)[1]; }
    else if (l.startsWith('BITMAP')) { inBitmap = true; rows = []; }
    else if (l.startsWith('ENDCHAR')) {
      if (enc >= FIRST && enc <= LAST) glyphs.set(enc, rows.slice(0, H));
      inBitmap = false; enc = -1;
    } else if (inBitmap) { rows.push(l.trim()); }
  }
  const data = [];
  for (let c = FIRST; c <= LAST; c++) {
    const rowsHex = glyphs.get(c) || [];
    for (let r = 0; r < H; r++) {
      const hex = rowsHex[r] || '';
      for (let b = 0; b < bpr; b++) {
        const byteHex = hex.substr(b * 2, 2);
        data.push(byteHex.length === 2 ? parseInt(byteHex, 16) : 0);
      }
    }
  }
  console.log(`${name}: ${W}x${H} bpr=${bpr} glyphs=${glyphs.size}/${N} bytes=${data.length}`);
  return { name, W, H, bpr, data };
}

// --- Rasterize a curved typeface to a PROPORTIONAL H-tall 1-bit font via headless Chrome.
// Each glyph is left-aligned in a fixed-width cell (W = widest advance) but carries its own
// advance width in `widths[]`, so TextOperator spaces glyphs naturally instead of monospace. ---
async function rasterizeFont(name, H, fontStack, fontSize) {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage();
  const res = await page.evaluate(({ FIRST, LAST, H, fontStack, fontSize }) => {
    const probe = document.createElement('canvas').getContext('2d');
    probe.font = `${fontSize}px ${fontStack}`;
    // Advance width per glyph (typographic spacing, includes side bearings).
    const widths = [];
    let maxAdv = 1;
    for (let c = FIRST; c <= LAST; c++) {
      const a = Math.max(1, Math.round(probe.measureText(String.fromCharCode(c)).width));
      widths.push(a); if (a > maxAdv) maxAdv = a;
    }
    const W = maxAdv + 1;              // cell wide enough to hold the widest glyph's ink
    const baseY = H - 7;               // baseline; leaves room for descenders
    const cvs = document.createElement('canvas'); cvs.width = W; cvs.height = H;
    const ctx = cvs.getContext('2d', { willReadFrequently: true });
    const bpr = Math.ceil(W / 8);
    const out = [];
    for (let c = FIRST; c <= LAST; c++) {
      ctx.clearRect(0, 0, W, H);
      ctx.font = `${fontSize}px ${fontStack}`;
      ctx.textAlign = 'left';          // pen at x=0; natural left side bearing preserved
      ctx.textBaseline = 'alphabetic';
      ctx.fillStyle = '#fff';
      ctx.fillText(String.fromCharCode(c), 0, baseY);
      const px = ctx.getImageData(0, 0, W, H).data;
      for (let y = 0; y < H; y++) {
        for (let b = 0; b < bpr; b++) {
          let byte = 0;
          for (let bit = 0; bit < 8; bit++) {
            const x = b * 8 + bit;
            if (x < W && px[(y * W + x) * 4 + 3] >= 110) byte |= 0x80 >> bit;
          }
          out.push(byte);
        }
      }
    }
    return { W, bpr, data: out, widths };
  }, { FIRST, LAST, H, fontStack, fontSize });
  await browser.close();
  console.log(`${name}: ${res.W}x${H} bpr=${res.bpr} proportional (${fontStack} @${fontSize}px) bytes=${res.data.length}`);
  return { name, W: res.W, H, bpr: res.bpr, data: res.data, widths: res.widths };
}

const fonts = [
  parseBdf(await ensureBdf('5x8'), 'FONT_5x8'),
  parseBdf(await ensureBdf('8x16'), 'FONT_8x16'),
  await rasterizeFont('FONT_16x32', 32, "'Helvetica Neue', Helvetica, Arial, sans-serif", 30),
];

let out = `#pragma once
// GENERATED by scripts/gen-fonts.mjs. Do not edit.
// FONT_5x8 / FONT_8x16: Spleen (BSD-2-Clause, (c) Frederic Cambus). FONT_16x32: Helvetica/Arial
// rasterized to 1-bit via Chrome. Printable ASCII ${FIRST}..${LAST} (${N} glyphs), row-major,
// MSB-first (pixel x -> bit 0x80>>(x&7)).
#include <cstdint>
namespace TextFonts {
// widths == nullptr → monospace (advance = w); else per-glyph advance table (proportional).
struct BitmapFont { uint8_t w, h, bytesPerRow; const uint8_t* data; const uint8_t* widths; };
static const int FIRST_CHAR = ${FIRST};
static const int NUM_GLYPHS = ${N};
`;
for (const f of fonts) {
  out += `static const uint8_t ${f.name}_DATA[] = {\n`;
  for (let i = 0; i < f.data.length; i += 24) {
    out += '  ' + f.data.slice(i, i + 24).map((b) => '0x' + b.toString(16).padStart(2, '0')).join(',') + ',\n';
  }
  out += `};\n`;
  let widthsRef = 'nullptr';
  if (f.widths) {
    widthsRef = `${f.name}_WIDTHS`;
    out += `static const uint8_t ${widthsRef}[] = {${f.widths.join(',')}};\n`;
  }
  out += `static const BitmapFont ${f.name} = {${f.W}, ${f.H}, ${f.bpr}, ${f.name}_DATA, ${widthsRef}};\n`;
}
out += `}\n`;
writeFileSync('native/text_fonts.h', out);
console.log('wrote native/text_fonts.h (' + out.length + ' bytes)');
