// Generate native/text_fonts.h from Spleen BDF fonts (BSD-2-Clause, Frédéric Cambus).
// Extracts printable ASCII 32..126 (95 glyphs) for a few monospace sizes into flat,
// row-major, MSB-first bitmap arrays the TextOperator can index. Run:
//   for s in 5x8 8x16 16x32; do curl -so /tmp/spleen-$s.bdf \
//     https://raw.githubusercontent.com/fcambus/spleen/master/spleen-$s.bdf; done
//   node scripts/gen-fonts.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const FIRST = 32, LAST = 126, N = LAST - FIRST + 1;

function parseBdf(path, name) {
  const lines = readFileSync(path, 'utf8').split('\n');
  let W = 0, H = 0;
  for (const l of lines) if (l.startsWith('FONTBOUNDINGBOX')) { const p = l.split(/\s+/); W = +p[1]; H = +p[2]; break; }
  const bpr = Math.ceil(W / 8);
  const glyphs = new Map();
  let enc = -1, inBitmap = false, rows = [];
  for (const l of lines) {
    if (l.startsWith('ENCODING')) { enc = +l.split(/\s+/)[1]; }
    else if (l.startsWith('BITMAP')) { inBitmap = true; rows = []; }
    else if (l.startsWith('ENDCHAR')) {
      if (enc >= FIRST && enc <= LAST) glyphs.set(enc, rows.slice(0, H));
      inBitmap = false; enc = -1;
    } else if (inBitmap) { rows.push(l.trim()); }
  }
  // Flatten to (N * H * bpr) bytes, in char order, zero-filled for any missing glyph/row.
  const data = [];
  for (let c = FIRST; c <= LAST; c++) {
    const rowsHex = glyphs.get(c) || [];
    for (let r = 0; r < H; r++) {
      const hex = rowsHex[r] || '';
      for (let b = 0; b < bpr; b++) {
        const byteHex = hex.substr(b * 2, 2);
        data.push(byteHex.length === 2 ? parseInt(byteHex, 16) : 0);
      }
    }
  }
  const missing = []; for (let c = FIRST; c <= LAST; c++) if (!glyphs.has(c)) missing.push(c);
  if (missing.length) console.warn(`${name}: missing glyphs ${missing.join(',')}`);
  console.log(`${name}: ${W}x${H} bpr=${bpr} glyphs=${glyphs.size}/${N} bytes=${data.length}`);
  return { name, W, H, bpr, data };
}

const fonts = [
  parseBdf('/tmp/spleen-5x8.bdf', 'FONT_5x8'),
  parseBdf('/tmp/spleen-8x16.bdf', 'FONT_8x16'),
  parseBdf('/tmp/spleen-16x32.bdf', 'FONT_16x32'),
];

let out = `#pragma once
// GENERATED by scripts/gen-fonts.mjs from Spleen (BSD-2-Clause, (c) Frédéric Cambus). Do not edit.
// Printable ASCII ${FIRST}..${LAST} (${N} glyphs), row-major, MSB-first (pixel x -> bit 0x80>>(x&7)).
#include <cstdint>
namespace TextFonts {
struct BitmapFont { uint8_t w, h, bytesPerRow; const uint8_t* data; };
static const int FIRST_CHAR = ${FIRST};
static const int NUM_GLYPHS = ${N};
`;
for (const f of fonts) {
  out += `static const uint8_t ${f.name}_DATA[] = {\n`;
  for (let i = 0; i < f.data.length; i += 24) {
    out += '  ' + f.data.slice(i, i + 24).map((b) => '0x' + b.toString(16).padStart(2, '0')).join(',') + ',\n';
  }
  out += `};\nstatic const BitmapFont ${f.name} = {${f.W}, ${f.H}, ${f.bpr}, ${f.name}_DATA};\n`;
}
out += `}\n`;
writeFileSync('native/text_fonts.h', out);
console.log('wrote native/text_fonts.h (' + out.length + ' bytes)');
