// Generate native/text_fonts.h.
//   - FONT_5x8 / FONT_8x16: Spleen BDF (BSD-2-Clause, Frédéric Cambus) — crisp pixel fonts,
//     ideal at tiny sizes where anti-aliasing would just muddy things.
//   - FONT_16x32: rasterized from a real curved sans-serif (Helvetica/Arial) via headless
//     Chrome, thresholded to 1-bit. Spleen's 16x32 was boxy/hard to read at size; a true
//     typeface with curves reads far better on a 40px-tall display.
// Run:  node scripts/gen-fonts.mjs   (auto-downloads the Spleen BDFs to /tmp if missing)
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { chromium } from 'playwright';

const FIRST = 32, LAST = 126, N = LAST - FIRST + 1;

async function ensureBdf(size) {
  const path = `/tmp/spleen-${size}.bdf`;
  if (existsSync(path)) return path;
  const url = `https://raw.githubusercontent.com/fcambus/spleen/master/spleen-${size}.bdf`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch ${url}: ${res.status}`);
  writeFileSync(path, Buffer.from(await res.arrayBuffer()));
  return path;
}

// --- Spleen BDF → flat row-major MSB-first bitmap (unchanged from the original) ---
function parseBdf(path, name) {
  const lines = readFileSync(path, 'utf8').split('\n');
  let W = 0, H = 0;
  for (const l of lines) if (l.startsWith('FONTBOUNDINGBOX')) { const p = l.split(/\s+/); W = +p[1]; H = +p[2]; break; }
  const bpr = Math.ceil(W / 8);
  const glyphs = new Map();
  let enc = -1, inBitmap = false, rows = [];
  for (const l of lines) {
    if (l.startsWith('ENCODING')) { enc = +l.split(/\s+/)[1]; }
    else if (l.startsWith('BITMAP')) { inBitmap = true; rows = []; }
    else if (l.startsWith('ENDCHAR')) {
      if (enc >= FIRST && enc <= LAST) glyphs.set(enc, rows.slice(0, H));
      inBitmap = false; enc = -1;
    } else if (inBitmap) { rows.push(l.trim()); }
  }
  const data = [];
  for (let c = FIRST; c <= LAST; c++) {
    const rowsHex = glyphs.get(c) || [];
    for (let r = 0; r < H; r++) {
      const hex = rowsHex[r] || '';
      for (let b = 0; b < bpr; b++) {
        const byteHex = hex.substr(b * 2, 2);
        data.push(byteHex.length === 2 ? parseInt(byteHex, 16) : 0);
      }
    }
  }
  console.log(`${name}: ${W}x${H} bpr=${bpr} glyphs=${glyphs.size}/${N} bytes=${data.length}`);
  return { name, W, H, bpr, data };
}

// --- Rasterize a curved typeface to a fixed W×H 1-bit cell via headless Chrome ---
async function rasterizeFont(name, W, H, fontStack, fontSize) {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage();
  const data = await page.evaluate(({ FIRST, LAST, W, H, fontStack, fontSize }) => {
    const cvs = document.createElement('canvas');
    cvs.width = W; cvs.height = H;
    const ctx = cvs.getContext('2d', { willReadFrequently: true });
    const maxInk = W - 1;          // leave a 1px right gutter between monospace cells
    const baseY = H - 6;           // baseline: room for descenders below
    const out = [];
    for (let c = FIRST; c <= LAST; c++) {
      ctx.clearRect(0, 0, W, H);
      const ch = String.fromCharCode(c);
      ctx.font = `${fontSize}px ${fontStack}`;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'alphabetic';
      const m = ctx.measureText(ch);
      const inkW = (m.actualBoundingBoxLeft || 0) + (m.actualBoundingBoxRight || 0);
      const sx = inkW > maxInk ? maxInk / inkW : 1;   // condense only glyphs too wide to fit
      ctx.save();
      ctx.translate(W / 2, baseY);
      ctx.scale(sx, 1);
      ctx.fillStyle = '#fff';
      ctx.fillText(ch, 0, 0);
      ctx.restore();
      const px = ctx.getImageData(0, 0, W, H).data;
      const bpr = Math.ceil(W / 8);
      for (let y = 0; y < H; y++) {
        for (let b = 0; b < bpr; b++) {
          let byte = 0;
          for (let bit = 0; bit < 8; bit++) {
            const x = b * 8 + bit;
            if (x < W) {
              const a = px[(y * W + x) * 4 + 3];      // alpha
              if (a >= 110) byte |= 0x80 >> bit;       // 1-bit threshold
            }
          }
          out.push(byte);
        }
      }
    }
    return out;
  }, { FIRST, LAST, W, H, fontStack, fontSize });
  await browser.close();
  const bpr = Math.ceil(W / 8);
  console.log(`${name}: ${W}x${H} bpr=${bpr} (rasterized ${fontStack} @${fontSize}px) bytes=${data.length}`);
  return { name, W, H, bpr, data };
}

const fonts = [
  parseBdf(await ensureBdf('5x8'), 'FONT_5x8'),
  parseBdf(await ensureBdf('8x16'), 'FONT_8x16'),
  await rasterizeFont('FONT_16x32', 16, 32, "'Helvetica Neue', Helvetica, Arial, sans-serif", 30),
];

let out = `#pragma once
// GENERATED by scripts/gen-fonts.mjs. Do not edit.
// FONT_5x8 / FONT_8x16: Spleen (BSD-2-Clause, (c) Frederic Cambus). FONT_16x32: Helvetica/Arial
// rasterized to 1-bit via Chrome. Printable ASCII ${FIRST}..${LAST} (${N} glyphs), row-major,
// MSB-first (pixel x -> bit 0x80>>(x&7)).
#include <cstdint>
namespace TextFonts {
struct BitmapFont { uint8_t w, h, bytesPerRow; const uint8_t* data; };
static const int FIRST_CHAR = ${FIRST};
static const int NUM_GLYPHS = ${N};
`;
for (const f of fonts) {
  out += `static const uint8_t ${f.name}_DATA[] = {\n`;
  for (let i = 0; i < f.data.length; i += 24) {
    out += '  ' + f.data.slice(i, i + 24).map((b) => '0x' + b.toString(16).padStart(2, '0')).join(',') + ',\n';
  }
  out += `};\nstatic const BitmapFont ${f.name} = {${f.W}, ${f.H}, ${f.bpr}, ${f.name}_DATA};\n`;
}
out += `}\n`;
writeFileSync('native/text_fonts.h', out);
console.log('wrote native/text_fonts.h (' + out.length + ' bytes)');
